### ISSUE TITLE
Templates without a summary is broken

### ISSUE THREAD

**Issue by Raghed22** [iLert/terraform-provider-ilert#24]
If you decide to skip the templates summary (Which is not required) you'll end up with Incidents that can not be resolved.
And since the summary/title bar is gray in the ui you don't see that there is a box which you can type in summary.
Ilert should either are stop caring about the summary or make it required.

**Comment by krystianity** [comment]
Hi @Raghed22 thank you for providing feedback.

We were tweaking the incident template summaries to allow for additional use cases around incident update notifications with templates, however we have come to the conclusion that template summaries need to be required fields as well - it will be fixed with the next release.
